name: Release
on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io

jobs:

  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@github.com"

    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Yarn
      run: yarn

    - name: Build website
      run: yarn build

    - name: create CNAME file with kndp.io domain
      run: echo kndp.io > CNAME
 
  deploy:
    needs: build

    permissions:
      pages: write  
      id-token: write 

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: build